name: Weekly link check
on:
  schedule:
    - cron: "5 0 * * 2" # 00:05 on Tuesday
  workflow_dispatch: # on demand launches, if needed

# Allow simultaneous checks
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check broken links in the README
      if: runner.os == 'Linux'
      uses: lycheeverse/lychee-action@v2
      with:
        args: "-n README.md"
        output: "/dev/stdout"
        fail: true
        failIfEmpty: false
